name: Code Quality Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2

      # Step 5: Run Detekt for Kotlin code quality
      - name: Run Detekt
        run: ./gradlew detekt
        continue-on-error: false

      # Step 6: Run Android Lint
      - name: Run Android Lint
        run: ./gradlew lintDebug
        continue-on-error: false

      # Step 7: Run SonarQube analysis (Optional, requires SonarQube setup)
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube -Dsonar.projectKey=your_project_key -Dsonar.host.url=https://sonarcloud.io
